# Generated by Django 4.1.2 on 2022-10-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="deliveried_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="shiped_at",
        ),
    ]
