# Generated by Django 4.1.2 on 2022-10-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_deliveried_at_and_more"),
        ("products", "0001_initial"),
        ("orders", "0003_alter_order_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(default="test", verbose_name="배송지 주소"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", to="products.product", verbose_name="주문상품"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="payments.payment",
                verbose_name="결재",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payed", "결제완료"),
                    ("sent", "발송완료"),
                    ("arrived", "배송완료"),
                    ("cancel", "결제취소"),
                    ("refund", "환불"),
                ],
                default="payed",
                max_length=7,
                verbose_name="상태",
            ),
        ),
    ]
