# Generated by Django 4.1.2 on 2022-10-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("thumbnail", models.ImageField(upload_to="", verbose_name="썸네일")),
                ("name", models.CharField(max_length=30, verbose_name="상품명")),
                ("description", models.TextField(verbose_name="상품 설명")),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                (
                    "pre_sale_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="세일 전 가격"
                    ),
                ),
                (
                    "is_waiting",
                    models.BooleanField(default=False, verbose_name="판매 대기 여부"),
                ),
                (
                    "is_best",
                    models.BooleanField(default=False, verbose_name="베스트 상품 여부"),
                ),
                ("is_md", models.BooleanField(default=False, verbose_name="MD 상품 여부")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="재고")),
                ("country", models.CharField(max_length=20, verbose_name="원산지")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("parcel", "택배")], max_length=6, verbose_name="배송방법"
                    ),
                ),
                (
                    "delivery_price",
                    models.PositiveIntegerField(default=0, verbose_name="배송비"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="", verbose_name="상품 상세 사진")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
